
#This code is used to generate the PhysiCell tumors examined in Figure 4 of Lewinsohn et al 2022, https://doi.org/10.1101/2022.08.05.502978

#The PhysiCell section of the code is a minorly modified version of that released by Ghaffarizadeh et al 2018.
#It includes bespoke printing functions, and has mutation capabilities that affect just one daughter cell instead of both
#which required tinkering with some of the core code functionality instead of just creating external classes. 
#Differences in the core code (i.e., anything in PhysiCell/core) are marked by a commented 'AFFEDER addition'
#The custom class tumor_evolve, which can be found in sample_projects, is also created for this manuscript
#This is also a full PhysiCell build, so there's a lot here that does not directly impact the how tumor_evolve works

#This version of PhysiCell should run as self-contained. 
#You'll need to compile it before you reach the *** commands below
#To do this, cd into the PhysiCell directory and run the following:

#make clean
#make reset
#make tumor_evolve
#make

#You may run into an error similar to the following:
#  clang: error: unsupported option '-fopenmp'
#  make: *** [BioFVM_vector.o] Error 1
#
#which you'll need to resolve this by linking your compiler. For me, the following command resolves this:
# export PHYSICELL_CPP=/usr/local/bin/g++-10
#Please see the PhysiCell Quickstart documentation for more information:
# https://github.com/MathCancer/PhysiCell/blob/master/documentation/Quickstart.md
# (This link works as of July 29, 2022)

#Once the tumor_evolve PhysiCell build is compiled, the files generated by R will set up generating PhysiCell xmls
# and calling PhysiCell itself.
setwd("~/Documents/Github/PhysiCellTrees/code")

#The following five scripts create custom directories for the give different simulated models explored
#2D neutral boundary-driven growth
source('generate_2D_neut_tums_bdg.r')
#2D selective boundary-driven growth
source('generate_2D_sel_tums_bdg.r')
#3D neutral boundary-driven growth
source('generate_3D_neutral_tums.r')
#3D selection boundary-driven growth
source('generate_3D_sel_tums.r')
#2D neutral boundary-driven growth with motility
source('generate_2D_neut_tums_motility.r')




#For each of the give models, the above code does three major things:
#1) creates proper output directory structure in PhysiCellTrees/out
#2) creates a directory in PhysiCellTrees/code with an .r and .sge file
#      for running 8 PhysiCell tumors on a cluster node. In total, files
#      are created to run 25 PC tumors at each of 9 death rates 
#      (d = 0, 0.1, 0.2, ... 0.8). Mostly death rates are run together, 
#      but one file "dmult" runs a single iteration of multiple death rates.
#3) creates a file matching run_*.sh with all qsub commands that starts 
#      all the PhysiCell runs

#Note - the 'generate*.r' scripts call/rely on
# > setup_rscripts_and_sges.r
#You'll need to a specify your own directory in the 'generate_R_script' function and set it as 'dirpath'

#***At this point the PhysiCell tumors can be generated via the following three commands
system('run_2D_neut_bdg.sh')
system('run_2D_sel_bdg_highermu.sh')
system('run_3D_neut.sh')
system('run_3D_sel.sh')
system('run_2D_neut_bdg_motility.sh')


#It's possible you may need to manually set the permissions of these files before they will run

#NB - the above code requests a huge amount of cluster time and prints a large amount of data
#This relies on the script
# > 'design_PC_runs'

#Now, the tumors must be sampled according to some sampling scheme, which is specified in the below give scripts
#Ultimately, in the PhysiCell tumors, we only explore one sampling scheme and depth (diversified sampling,
# n = 100), but this would be the place to set up alternative sampling approaches
source('sample_3D_neut.r')
source('sample_2D_neut_bdg.r')
source('sample_2D_sel_bdg_highermu.r')
source('sample_3D_sel.r')
source('sample_2D_neut_bdg_motility.r')


#These rely on the scripts:
# > sample_tumor.r
# > PC_logs_to_trees.r

#Now, the actual sampling goes on via running the following three scripts
system('run_2D_neut_bdg.sh')
system('run_2D_sel_bdg_highermu.sh')
system('run_3D_neut.sh')
system('run_3D_sel_tums.sh')
system('run_2D_neut_tums_motility.sh')


#NB - if you didn't want to run all tumors, you could loop through all the .r files in 
#the 2D_neut_bdg/diversified_100/ 2D_sel_bdg_highermu/diversified_100/, and 3D_neut/diversified_100/
#directories. It's currently set up to be submitted to a cluster with batch submission
#
#To see how this works for 8 tumors, you can uncomment and run the following
#source("2D_neut_bdg/diversified_100/d0_dim2_w1_mu1_N10000_i1.r")


#As output at this point, you'll have five populated directories for each simulation/sampling scheme:
# 1. growth_rate_differences, which records the total number of edge and center cells and their birthrates
# 2. to_beast_format, which is what is used as input for the creation of xml files that will go to BEAST
# 3. with_hull_info, which is a large file that keeps track of the entire tumor history simulation, but adds
#    distance to the tumor hull, which is useful for computing edge/center statistics. 


